version: '3'

services:
  dwh:
    container_name: dwh
    image: postgres:16.3-alpine@sha256:7f7832dfb7770c7256fe3f8c4cb57617caee45e2494cc0a736594135237ed9bf
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - database.env

  etl:
    container_name: etl_service
    image: analytic-eng-challenge/etl:latest
    depends_on:
      - dwh
    command: ["./wait-for-it.sh", "dwh:5432", "--", "sh", "execute.sh"]
    build: 
      context: ./etl

volumes:
  db_data:
