version: '3'

services:
  dwh:
    container_name: dwh
    image: postgres:14.7-alpine@sha256:07985c5c5e01ee550b30c67a2cf806f8b08b32f74e3f24c4cbef31305ef5776d
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - database.env

  etl:
    container_name: etl_service
    image: analytic-eng-challenge/etl:latest
    depends_on:
      - dwh
    command: ["./wait-for-it.sh", "dwh:5432", "--", "sh", "execute.sh"]
    build: 
      context: ./etl

volumes:
  db_data:
